# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  boomi-report:
    runs-on: ubuntu-latest
    env:
      accountId: ${{ secrets.BOOMI_ACCOUNT_ID }}
      authToken: ${{ secrets.BOOMI_AUTH_TOKEN }}
      baseURL: ${{ secrets.BOOMI_BASE_URL }}/${{ secrets.BOOMI_ACCOUNT_ID }}
      gitComponentRepoURL: ${{ secrets.GIT_COMPONENT_REPO_URL }}
      gitComponentUserName: ${{ secrets.GIT_COMPONENT_USER_NAME }}
      gitComponentUserEmail: ${{ secrets.GIT_COMPONENT_USER_EMAIL }}
      h1: "Content-Type: application/json"
      h2: "Accept: application/json"
      WORKSPACE: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: jayeshpatel-23/lime-boomi-cicd
          path: cli
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq libxml2-utils
      - name: Generate Deployment Report
        run: |
          cd cli/bin
          ./getAllEnvironments.sh
          ./publishDeployedPackage.sh env=DEV > $WORKSPACE/deployment-report.html
      - name: Push Report to Artifacts Repo
        run: |
          git config --global user.email "${gitComponentUserEmail}"
          git config --global user.name "${gitComponentUserName}"
          git clone "${gitComponentRepoURL}" artifacts
          cp $WORKSPACE/deployment-report.html artifacts/
          cd artifacts
          git add .
          git commit -m "Add latest deployment report"
          git push
