name: Boomi CLI Smoke (envId)

on:
  workflow_dispatch:
    inputs:
      env_id:
        description: "Boomi Environment ID"
        required: true
        default: "dd7fcb9f-7c12-4f69-a320-5706f6d3d196"

jobs:
  smoke:
    runs-on: ubuntu-latest

    env:
      accountId: ${{ secrets.BOOMI_ACCOUNT_ID }}
      authToken: ${{ secrets.BOOMI_AUTH_TOKEN }}
      h1: "Content-Type: application/json"
      h2: "Accept: application/json"
      baseURL: "https://api.boomi.com/api/rest/v1/${{ secrets.BOOMI_ACCOUNT_ID }}"
      WORKSPACE: ${{ github.workspace }}/out
      VERBOSE: "false"
      SLEEP_TIMER: "0.2"

    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl libxml2-utils
          mkdir -p "$WORKSPACE"
          chmod +x bin/*.sh || true

      - name: Query Deployed Packages for EnvId
        run: |
          ENV_ID="${{ github.event.inputs.env_id }}"
          echo "Using envId=$ENV_ID"
          # Example: check a package, or just pull all with publishDeployedPackage
          ./bin/publishDeployedPackage.sh env=$ENV_ID > "$WORKSPACE/deployed-packages-${ENV_ID}.html"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployed-packages-${{ github.event.inputs.env_id }}
          path: out/
